<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Schema/cosmic-modules.proto

namespace WebTeam\Demo\Cosmic\Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>demo.Account</code>
 */
class Account extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>map<string, string> credentials = 1;</code>
     */
    private $credentials;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type array|\Google\Protobuf\Internal\MapField $credentials
     * }
     */
    public function __construct($data = NULL) {
        \WebTeam\Demo\Cosmic\Proto\Metadata\CosmicModules::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>map<string, string> credentials = 1;</code>
     * @return \Google\Protobuf\Internal\MapField
     */
    public function getCredentials()
    {
        return $this->credentials;
    }

    /**
     * Generated from protobuf field <code>map<string, string> credentials = 1;</code>
     * @param array|\Google\Protobuf\Internal\MapField $var
     * @return $this
     */
    public function setCredentials($var)
    {
        $arr = GPBUtil::checkMapField($var, \Google\Protobuf\Internal\GPBType::STRING, \Google\Protobuf\Internal\GPBType::STRING);
        $this->credentials = $arr;

        return $this;
    }

}

