<?php
# Generated by the protocol buffer compiler (roadrunner-server/grpc). DO NOT EDIT!
# source: Schema/cosmic-modules.proto

namespace WebTeam\Demo\Cosmic\Proto;

use Spiral\RoadRunner\GRPC;

interface CosmicSystemsInterface extends GRPC\ServiceInterface
{
    // GRPC specific service name.
    public const NAME = "demo.CosmicSystems";

    /**
    * @param GRPC\ContextInterface $ctx
    * @param StatusRequest $in
    * @return StatusResponse
    *
    * @throws GRPC\Exception\InvokeException
    */
    public function statusCommand(GRPC\ContextInterface $ctx, StatusRequest $in): StatusResponse;
}
