<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Schema/cosmic-modules.proto

namespace WebTeam\Demo\Cosmic\Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>demo.ErrorResponse</code>
 */
class ErrorResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.demo.Error error = 1;</code>
     */
    protected $error = null;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \WebTeam\Demo\Cosmic\Proto\Error $error
     * }
     */
    public function __construct($data = NULL) {
        \WebTeam\Demo\Cosmic\Proto\Metadata\CosmicModules::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.demo.Error error = 1;</code>
     * @return \WebTeam\Demo\Cosmic\Proto\Error|null
     */
    public function getError()
    {
        return $this->error;
    }

    public function hasError()
    {
        return isset($this->error);
    }

    public function clearError()
    {
        unset($this->error);
    }

    /**
     * Generated from protobuf field <code>.demo.Error error = 1;</code>
     * @param \WebTeam\Demo\Cosmic\Proto\Error $var
     * @return $this
     */
    public function setError($var)
    {
        GPBUtil::checkMessage($var, \WebTeam\Demo\Cosmic\Proto\Error::class);
        $this->error = $var;

        return $this;
    }

}

