<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Schema/cosmic-modules.proto

namespace WebTeam\Demo\Cosmic\Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>demo.ErrorResponse</code>
 */
class ErrorResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>int32 error = 1;</code>
     */
    protected $error = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type int $error
     * }
     */
    public function __construct($data = NULL) {
        \WebTeam\Demo\Cosmic\Proto\Metadata\CosmicModules::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>int32 error = 1;</code>
     * @return int
     */
    public function getError()
    {
        return $this->error;
    }

    /**
     * Generated from protobuf field <code>int32 error = 1;</code>
     * @param int $var
     * @return $this
     */
    public function setError($var)
    {
        GPBUtil::checkInt32($var);
        $this->error = $var;

        return $this;
    }

}

