<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Schema/cosmic-modules.proto

namespace WebTeam\Demo\Cosmic\Proto;

use UnexpectedValueException;

/**
 * Protobuf type <code>demo.Status</code>
 */
class Status
{
    /**
     * Generated from protobuf enum <code>UNDEFINED = 0;</code>
     */
    const UNDEFINED = 0;
    /**
     * Generated from protobuf enum <code>OFFLINE = 1;</code>
     */
    const OFFLINE = 1;
    /**
     * Generated from protobuf enum <code>BROADCASTING = 2;</code>
     */
    const BROADCASTING = 2;
    /**
     * Generated from protobuf enum <code>LISTENING = 3;</code>
     */
    const LISTENING = 3;
    /**
     * Generated from protobuf enum <code>SCHEDULING = 4;</code>
     */
    const SCHEDULING = 4;

    private static $valueToName = [
        self::UNDEFINED => 'UNDEFINED',
        self::OFFLINE => 'OFFLINE',
        self::BROADCASTING => 'BROADCASTING',
        self::LISTENING => 'LISTENING',
        self::SCHEDULING => 'SCHEDULING',
    ];

    public static function name($value)
    {
        if (!isset(self::$valueToName[$value])) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no name defined for value %s', __CLASS__, $value));
        }
        return self::$valueToName[$value];
    }


    public static function value($name)
    {
        $const = __CLASS__ . '::' . strtoupper($name);
        if (!defined($const)) {
            throw new UnexpectedValueException(sprintf(
                    'Enum %s has no value defined for name %s', __CLASS__, $name));
        }
        return constant($const);
    }
}

