<?php
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Schema/cosmic-modules.proto

namespace WebTeam\Demo\Cosmic\Proto;

use Google\Protobuf\Internal\GPBType;
use Google\Protobuf\Internal\RepeatedField;
use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>demo.StatusResponse</code>
 */
class StatusResponse extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>.demo.Error error = 1;</code>
     */
    protected $error = null;
    /**
     * Generated from protobuf field <code>.demo.Status status = 2;</code>
     */
    protected $status = 0;
    /**
     * Generated from protobuf field <code>int32 battery = 3;</code>
     */
    protected $battery = 0;

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type \WebTeam\Demo\Cosmic\Proto\Error $error
     *     @type int $status
     *     @type int $battery
     * }
     */
    public function __construct($data = NULL) {
        \WebTeam\Demo\Cosmic\Proto\Metadata\CosmicModules::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>.demo.Error error = 1;</code>
     * @return \WebTeam\Demo\Cosmic\Proto\Error|null
     */
    public function getError()
    {
        return $this->error;
    }

    public function hasError()
    {
        return isset($this->error);
    }

    public function clearError()
    {
        unset($this->error);
    }

    /**
     * Generated from protobuf field <code>.demo.Error error = 1;</code>
     * @param \WebTeam\Demo\Cosmic\Proto\Error $var
     * @return $this
     */
    public function setError($var)
    {
        GPBUtil::checkMessage($var, \WebTeam\Demo\Cosmic\Proto\Error::class);
        $this->error = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>.demo.Status status = 2;</code>
     * @return int
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * Generated from protobuf field <code>.demo.Status status = 2;</code>
     * @param int $var
     * @return $this
     */
    public function setStatus($var)
    {
        GPBUtil::checkEnum($var, \WebTeam\Demo\Cosmic\Proto\Status::class);
        $this->status = $var;

        return $this;
    }

    /**
     * Generated from protobuf field <code>int32 battery = 3;</code>
     * @return int
     */
    public function getBattery()
    {
        return $this->battery;
    }

    /**
     * Generated from protobuf field <code>int32 battery = 3;</code>
     * @param int $var
     * @return $this
     */
    public function setBattery($var)
    {
        GPBUtil::checkInt32($var);
        $this->battery = $var;

        return $this;
    }

}

